// Hand-written linking-only stub for ContextualMenuActions.Dlg9Oa2U.js (G23 case; original code).
// Read only inside the entry's component/hook bodies (the declared-GAP
// page/component exports); every use throws loudly.
const LL = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: ContextualMenuActions.LL.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: ContextualMenuActions.LL called — component-body-only`); } });
const aI = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: ContextualMenuActions.aI.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: ContextualMenuActions.aI called — component-body-only`); } });
const gt = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: ContextualMenuActions.gt.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: ContextualMenuActions.gt called — component-body-only`); } });
const hL = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: ContextualMenuActions.hL.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: ContextualMenuActions.hL called — component-body-only`); } });
const oF = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: ContextualMenuActions.oF.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: ContextualMenuActions.oF called — component-body-only`); } });
const pF = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: ContextualMenuActions.pF.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: ContextualMenuActions.pF called — component-body-only`); } });
const qP = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: ContextualMenuActions.qP.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: ContextualMenuActions.qP called — component-body-only`); } });
export { LL, aI, gt, hL, oF, pF, qP };
