// Hand-written linking-only stub for Issue.DRYymPCa.js (G23 case; original code).
// Read only inside the entry's component/hook bodies (the declared-GAP
// page/component exports); every use throws loudly.
const Aa = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.Aa.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.Aa called — component-body-only`); } });
const BS = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.BS.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.BS called — component-body-only`); } });
const E = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.E.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.E called — component-body-only`); } });
const G = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.G.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.G called — component-body-only`); } });
const HS = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.HS.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.HS called — component-body-only`); } });
const Tn = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.Tn.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.Tn called — component-body-only`); } });
const U = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.U.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.U called — component-body-only`); } });
const ar = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.ar.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.ar called — component-body-only`); } });
const xs = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G23 stub: Issue.xs.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G23 stub: Issue.xs called — component-body-only`); } });
export { Aa, BS, E, G, HS, Tn, U, ar, xs };
