// Hand-written linking-only stub for ContextualMenuActions.Dlg9Oa2U.js (G25 case; original code).
// Read only inside the entry's component body (the declared-GAP Component
// export); every use throws loudly.
const $P = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.$P.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.$P called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.$P constructed — component-body-only`); } });
const HP = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.HP.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.HP called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.HP constructed — component-body-only`); } });
const PP = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.PP.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.PP called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.PP constructed — component-body-only`); } });
const jI = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.jI.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.jI called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.jI constructed — component-body-only`); } });
const oF = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.oF.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.oF called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.oF constructed — component-body-only`); } });
const qP = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.qP.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.qP called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.qP constructed — component-body-only`); } });
const sF = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.sF.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.sF called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.sF constructed — component-body-only`); } });
const vI = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.vI.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.vI called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.vI constructed — component-body-only`); } });
const wP = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.wP.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.wP called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.wP constructed — component-body-only`); } });
const xP = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.xP.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.xP called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.xP constructed — component-body-only`); } });
const yP = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G25 stub: ContextualMenuActions.yP.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G25 stub: ContextualMenuActions.yP called — component-body-only`); }, construct(){ throw new Error(`G25 stub: ContextualMenuActions.yP constructed — component-body-only`); } });
export { $P, HP, PP, jI, oF, qP, sF, vI, wP, xP, yP };
