// Hand-written linking-only stub for useUsageLimitTableFilter.DeovAaha.js (G22 case; original code).
// Read only inside the entry's component/hook bodies (the declared-GAP
// Component export); every use throws loudly.
const a = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.a.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.a called — component-body-only`); } });
const i = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.i.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.i called — component-body-only`); } });
const l = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.l.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.l called — component-body-only`); } });
const n = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.n.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.n called — component-body-only`); } });
const o = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.o.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.o called — component-body-only`); } });
const r = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.r.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.r called — component-body-only`); } });
const s = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.s.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.s called — component-body-only`); } });
const t = new Proxy(function(){}, { get(_t, k){ if (typeof k === `symbol` || k === `displayName`) return undefined; throw new Error(`G22 stub: useUsageLimitTableFilter.t.${String(k)} read — component-body-only`); }, apply(){ throw new Error(`G22 stub: useUsageLimitTableFilter.t called — component-body-only`); } });
export { a, i, l, n, o, r, s, t };
